apiVersion: v1
kind: Service
metadata:
 name: mongo
 annotations:
   cloud.google.com/load-balancer-type: "Internal"
 labels:
   name: mongo
spec:
 ports:
   - port: 27017
     targetPort: 27017
     protocol: TCP
 type: LoadBalancer
 selector:
   app: mongo
   role: mongo
   environment: staging
 loadBalancerIP: 10.0.1.12
