kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: standard-retain
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
